# .github/workflows/ci.yml
name: CI

# Déclenche la CI sur chaque pull_request vers dev ou main
on:
  pull_request:
    branches: [ dev, main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupère ton code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Installe Node + cache npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3) Installe tes dépendances
      - name: Install dependencies
        run: npm ci

      # 4) Lint (ESLint + Prettier)
      - name: Lint
        run: npm run lint

      # 5) Exécute les tests
      - name: Test
        run: npm test -- --watchAll=false --bail

      # 6) Génère le build prod
      - name: Build
        run: npm run build
