spring.application.name=systeme-reservation-jo
spring.datasource.url=jdbc:postgresql://localhost:5432/reservation_jo
spring.datasource.username=anthony
spring.datasource.password=changemoi
# OK pour le developpement
spring.jpa.hibernate.ddl-auto=update
# Affiche les requetes SQL
spring.jpa.show-sql=true
#Formate le SQL
spring.jpa.properties.hibernate.format_sql=trues
# Change ca!
app.jwtSecret=UneCleSecreteVraimentTresLongueEtComplexe
# 24 heures
app.jwtExpirationInMs=86400000