spring.application.name=systeme-reservation-jo
spring.datasource.url=jdbc:postgresql://localhost:5432/reservation_jo
spring.datasource.username=anthony
spring.datasource.password=changemoi
spring.jpa.hibernate.ddl-auto=update