# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
        steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          cd systeme-reservation-jo-frontend
          npm ci

      - name: Lint
        run: |
          cd systeme-reservation-jo-frontend
          npm run lint

      - name: Test
        run: |
          cd systeme-reservation-jo-frontend
          npm test -- --watchAll=false --bail

      - name: Build
        run: |
          cd systeme-reservation-jo-frontend
          npm run build

